service: aw-lambda-crud-bm-cochabamba
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:513266450625:table/Products

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get
  createProduct:
    handler: src/addProduct.addProduct
    events:
      - httpApi:
          path: /products
          method: post
  getProducts:
    handler: src/getProducts.getProducts
    events:
      - httpApi:
          path: /products
          method: get
  getProduct:
    handler: src/getProduct.getProduct
    events:
      - httpApi:
          path: /product/{id}
          method: get
  updateProduct:
    handler: src/updateProduct.updateProduct
    events:
      - httpApi:
          path: /product/{id}
          method: put
  deleteProduct:
    handler: src/deleteProduct.deleteProduct
    events:
      - httpApi:
          path: /product/{id}
          method: delete

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH